"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const item_ctrl_1 = require("../controllers/item.ctrl");
const log_1 = require("../middlewares/log");
const router = (0, express_1.Router)();
exports.router = router;
router.get("/", item_ctrl_1.getItems);
router.get("/:id", log_1.logMiddleware, item_ctrl_1.getItem);
router.post("/", item_ctrl_1.postItem);
router.put("/:id", item_ctrl_1.updateItem);
router.delete("/:id", item_ctrl_1.deleteItem);
